const express=require('express');const cors=require('cors');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const {Pool}=require('pg');
const app=express();app.use(cors());app.use(express.json());
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const JWT_SECRET=process.env.JWT_SECRET||'change-this-in-render';const ADMIN_KEY=process.env.ADMIN_KEY||'set-an-admin-key';
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,mode TEXT NOT NULL,size INT NOT NULL,price NUMERIC(10,2) NOT NULL,payment_ref TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT now(),approved_at TIMESTAMPTZ);CREATE TABLE IF NOT EXISTS accounts(id SERIAL PRIMARY KEY,user_id INT REFERENCES users(id) ON DELETE CASCADE,account_no TEXT UNIQUE NOT NULL,mode TEXT NOT NULL,size INT NOT NULL,balance NUMERIC(14,2) NOT NULL,equity NUMERIC(14,2) NOT NULL,total_pnl NUMERIC(14,2) NOT NULL DEFAULT 0,daily_pnl NUMERIC(14,2) NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ DEFAULT now());CREATE TABLE IF NOT EXISTS trades(id SERIAL PRIMARY KEY,account_id INT REFERENCES accounts(id) ON DELETE CASCADE,direction TEXT NOT NULL,amount NUMERIC(14,2) NOT NULL,entry_price NUMERIC(14,2) NOT NULL,exit_price NUMERIC(14,2) NOT NULL,result TEXT NOT NULL,pnl NUMERIC(14,2) NOT NULL,expiry TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT now());`)}
const prices={1000:22,2000:40,5000:80,10000:150};const sizes=[1000,2000,5000,10000];function token(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:'7d'})}async function auth(req,res,next){try{const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):'';req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Authentication required'})}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'FundedEdge API',time:new Date().toISOString()}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password}=req.body;if(!name||!email||!password||password.length<8)return res.status(400).json({error:'Name, email and an 8+ character password are required'});const hash=await bcrypt.hash(password,12);const r=await pool.query('INSERT INTO users(name,email,password_hash) VALUES($1,$2,$3) RETURNING id,name,email',[name,email.toLowerCase().trim(),hash]);res.json({token:token(r.rows[0]),user:r.rows[0]})}catch(e){res.status(400).json({error:e.code==='23505'?'Email already registered':'Registration failed'})}});
app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body;const r=await pool.query('SELECT * FROM users WHERE email=$1',[String(email||'').toLowerCase().trim()]);if(!r.rows[0]||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Invalid email or password'});const u=r.rows[0];res.json({token:token(u),user:{id:u.id,name:u.name,email:u.email}})}catch(e){res.status(500).json({error:'Login failed'})}});
app.get('/api/me',auth,async(req,res)=>{const u=await pool.query('SELECT id,name,email,created_at FROM users WHERE id=$1',[req.user.id]);const a=await pool.query('SELECT * FROM accounts WHERE user_id=$1 ORDER BY id DESC',[req.user.id]);res.json({user:u.rows[0],accounts:a.rows})});
app.post('/api/orders',auth,async(req,res)=>{const {mode,size,price,paymentRef}=req.body;if(!['1 Step','2 Step'].includes(mode)||!sizes.includes(Number(size))||Number(price)!==prices[Number(size)])return res.status(400).json({error:'Invalid challenge'});const r=await pool.query('INSERT INTO orders(user_id,mode,size,price,payment_ref) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.user.id,mode,size,price,paymentRef||null]);res.json({order:r.rows[0]})});
app.get('/api/orders',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM orders WHERE user_id=$1 ORDER BY id DESC',[req.user.id]);res.json({orders:r.rows})});
app.get('/api/accounts/:id',auth,async(req,res)=>{const r=await pool.query('SELECT * FROM accounts WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:'Account not found'});const t=await pool.query('SELECT * FROM trades WHERE account_id=$1 ORDER BY id DESC LIMIT 100',[req.params.id]);res.json({account:r.rows[0],trades:t.rows})});
app.post('/api/trades',auth,async(req,res)=>{try{const {accountId,direction,amount,expiry}=req.body;const a=await pool.query('SELECT * FROM accounts WHERE id=$1 AND user_id=$2 AND status=$3',[accountId,req.user.id,'active']);if(!a.rows[0])return res.status(404).json({error:'Active account not found'});if(!['CALL','PUT'].includes(direction)||!['60s','5m','15m'].includes(expiry))return res.status(400).json({error:'Invalid trade'});const amt=Number(amount);if(!Number.isFinite(amt)||amt<=0||amt>a.rows[0].balance*0.2)return res.status(400).json({error:'Invalid trade amount'});const entry=67482.10+(Math.random()-.5)*100;const move=(Math.random()-.5)*120;const exit=entry+move;const win=direction==='CALL'?exit>entry:exit<entry;const pnl=win?amt*0.8:-amt;const result=win?'WIN':'LOSS';const nr=await pool.query('INSERT INTO trades(account_id,direction,amount,entry_price,exit_price,result,pnl,expiry) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[accountId,direction,amt,entry,exit,result,pnl,expiry]);await pool.query('UPDATE accounts SET balance=balance+$1,equity=equity+$1,total_pnl=total_pnl+$1,daily_pnl=daily_pnl+$1 WHERE id=$2',[pnl,accountId]);res.json({trade:nr.rows[0]})}catch(e){res.status(500).json({error:'Trade failed'})}});
function admin(req,res,next){if(req.headers['x-admin-key']!==ADMIN_KEY)return res.status(403).json({error:'Admin access denied'});next()}
app.get('/api/admin/orders',admin,async(req,res)=>{const r=await pool.query('SELECT o.*,u.name,u.email FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC');res.json({orders:r.rows})});
app.post('/api/admin/orders/:id/approve',admin,async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const o=(await c.query('SELECT * FROM orders WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!o)throw Error('Order not found');if(o.status==='approved'){await c.query('COMMIT');return res.json({ok:true,message:'Already approved'})}const no='FE-'+String(Date.now()).slice(-7)+String(Math.floor(Math.random()*90+10));const a=await c.query('INSERT INTO accounts(user_id,account_no,mode,size,balance,equity,total_pnl) VALUES($1,$2,$3,$4,$4, $4,0) RETURNING *',[o.user_id,no,o.mode,o.size]);await c.query("UPDATE orders SET status='approved',approved_at=now() WHERE id=$1",[o.id]);await c.query('COMMIT');res.json({ok:true,account:a.rows[0]})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.message})}finally{c.release()}});
app.post('/api/admin/orders/:id/reject',admin,async(req,res)=>{await pool.query("UPDATE orders SET status='rejected' WHERE id=$1",[req.params.id]);res.json({ok:true})});
const port=process.env.PORT||10000;init().then(()=>app.listen(port,()=>console.log('FundedEdge API listening on '+port))).catch(e=>{console.error(e);process.exit(1)});